// Speak one line.
//
// The browser asks here only when it could not find the clip in the bucket itself, so this is the
// slow path by design: synthesise, store it so nobody ever waits for this line again, and hand it
// back. Most of the course is pre-generated by tools/pregen-audio.mjs and never reaches this file.
//
// Дверь заперта. Раньше эта функция отвечала кому угодно без входа: синтез идёт через чужой
// сервис, а готовый файл пишется в хранилище владельца СЛУЖЕБНЫМ ключом. То есть посторонний мог
// залить туда сколько угодно своего текста, навсегда и за чужой счёт. Теперь — только вошедшие,
// и не больше разумного за сутки. Гость не остаётся без звука: курс озвучен заранее и читается
// из бакета напрямую, а на непредсказанной строке у него говорит голос браузера.
import { cacheKey, synthesise, putClip, publicUrl } from "../../lib/tts.mjs";
import { configured, learnerFromRequest, takeQuota } from "../../lib/supa.mjs";

const MAX_TEXT = 600;

// Сколько новых, ещё не озвученных строк один человек может заказать за сутки.
//
// Курс озвучен заранее целиком, так что в обычный день сюда прилетает несколько реплик Мии и
// ничего больше. 400 — потолок, о который живой человек не споткнётся.
const DAILY_CLIPS = 400;

// Голос выбирается не текстом из запроса, а из списка. Иначе поле `voice` — это способ гонять
// чужой сервис по любым голосам всех языков мира, а заодно плодить в бакете по клипу на каждый.
// Ровно то, что умеет попросить сайт: пять голосов из выбора в кабинете (VOICES в
// public/js/speech.js) плюс два запасных для родного языка. Список сверяется тестом —
// tools/test-voices.mjs, — иначе новый голос в кабинете молча подменялся бы на Серафину.
export const VOICES = new Set([
  "de-DE-SeraphinaMultilingualNeural",
  "de-DE-AmalaNeural",
  "de-DE-KatjaNeural",
  "de-AT-IngridNeural",
  "de-CH-LeniNeural",
  "ru-RU-SvetlanaNeural",
  "az-AZ-BanuNeural",
]);
export const LOCALES = new Set(["", "ru-RU", "az-AZ"]);

const clamp = (v, lo, hi) => Math.min(hi, Math.max(lo, Number.isFinite(v) ? v : 0));

const json = (body, status = 200) =>
  new Response(JSON.stringify(body), { status, headers: { "content-type": "application/json; charset=utf-8" } });

export default async (req) => {
  if (req.method !== "POST") return json({ error: "POST only" }, 405);

  const url = process.env.SUPABASE_URL;
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

  // Не можем проверить, кто пришёл, — не синтезируем. Как и у Мии: проверка, которая исчезает
  // вместе с настройками, — это не проверка.
  if (!configured()) return json({ error: "Озвучка сейчас не настроена." }, 503);
  let learner;
  try {
    learner = await learnerFromRequest(req);
  } catch {
    return json({ error: "Не получается проверить аккаунт." }, 503);
  }
  if (!learner) return json({ error: "Голос Мии — для тех, кто вошёл.", needsAuth: true }, 401);
  if (learner.blocked) return json({ error: "Аккаунт заблокирован." }, 403);

  let body;
  try { body = await req.json(); } catch { return json({ error: "bad body" }, 400); }

  const text = String(body?.text ?? "").trim().slice(0, MAX_TEXT);
  if (!text) return json({ error: "text required" }, 400);

  const voice = VOICES.has(String(body?.voice)) ? String(body.voice) : "de-DE-SeraphinaMultilingualNeural";
  const locale = LOCALES.has(String(body?.locale ?? "")) ? String(body?.locale ?? "") : "";
  // Пределы те же, что умеет настроить сам сайт (см. presetById в public/js/speech.js). За ними
  // голос звучит не «медленнее», а неразборчиво — и это ещё один ключ кэша на каждое значение.
  const rate = clamp(Number(body?.rate), -50, 50);
  const pitch = clamp(Number(body?.pitch), -50, 50);
  const volume = clamp(Number(body?.volume), -50, 50);
  // Личная реплика в разговоре. Её просят один раз и больше никогда — хранить её вечно в общем
  // бакете незачем, а вот попасть она туда могла бы навсегда.
  const store = body?.store !== false;

  const key = cacheKey(voice, rate, text, pitch, volume, locale);

  // Somebody may have asked for this exact line while the browser was checking; send it there.
  if (url && store) {
    const cached = await fetch(publicUrl(url, key), { method: "HEAD" }).then((r) => r.ok).catch(() => false);
    if (cached) return Response.redirect(publicUrl(url, key), 302);
  }

  if (!(await takeQuota(learner.id, "tts", DAILY_CLIPS))) {
    return json({ error: "Слишком много новых реплик за сегодня. Голос вернётся завтра." }, 429);
  }

  let audio;
  try {
    // Бюджет — чтобы две попытки не сложились в 46 секунд, а не потому что платформа торопит:
    // у обычной функции Netlify 60 секунд. Двадцати хватает на подключение и на повтор, если
    // сервис голоса ответил пустотой, — а человек за это время всё равно уже читает текст.
    audio = await synthesise({ text, voice, locale, rate, pitch, volume, budgetMs: 20000 });
  } catch (e) {
    console.error("[tts]", e?.message || e);
    // The app falls back to the browser's own voice on any failure here, so this must be quick
    // and honest rather than retried until the function times out.
    return json({ error: "Голос сейчас недоступен." }, 503);
  }

  // Дожидаемся записи, а не «отпускаем и забываем».
  //
  // Раньше здесь стоял putClip(...).catch(...) без await. На Netlify это лотерея: платформа
  // замораживает функцию сразу после ответа, и незавершённая запись просто не происходит — клип
  // не попадает в бакет, а следующий человек снова ждёт синтеза той же строки. Полторы секунды
  // на загрузку 30 КБ есть всегда; если не уложились — отдаём звук и идём дальше, слушатель
  // ничего не теряет.
  if (url && serviceKey && store) {
    await Promise.race([
      putClip(url, serviceKey, key, audio, { attempts: 2 }).catch((e) => console.error("[tts] store", e?.message || e)),
      new Promise((res) => setTimeout(res, 2000)),
    ]);
  }

  return new Response(audio, {
    headers: {
      "content-type": "audio/mpeg",
      // Личную реплику браузеру и посредникам кэшировать незачем — она звучит один раз.
      "cache-control": store ? "public, max-age=31536000, immutable" : "no-store",
      "x-tts-key": key,
    },
  });
};

export const config = { path: "/api/tts" };
