// Speak one line.
//
// The browser asks here only when it could not find the clip in the bucket itself, so this is the
// slow path by design: synthesise, store it so nobody ever waits for this line again, and hand it
// back. Most of the course is pre-generated by tools/pregen-audio.mjs and never reaches this file.
import { cacheKey, synthesise, putClip, publicUrl } from "../../lib/tts.mjs";

const MAX_TEXT = 600;
const json = (body, status = 200) =>
  new Response(JSON.stringify(body), { status, headers: { "content-type": "application/json; charset=utf-8" } });

export default async (req) => {
  if (req.method !== "POST") return json({ error: "POST only" }, 405);

  const url = process.env.SUPABASE_URL;
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

  let body;
  try { body = await req.json(); } catch { return json({ error: "bad body" }, 400); }

  const text = String(body?.text ?? "").trim().slice(0, MAX_TEXT);
  if (!text) return json({ error: "text required" }, 400);
  const voice = String(body?.voice || "de-DE-SeraphinaMultilingualNeural");
  const locale = String(body?.locale || "");
  const rate = Number(body?.rate) || 0;
  const pitch = Number(body?.pitch) || 0;
  const volume = Number(body?.volume) || 0;
  const key = cacheKey(voice, rate, text, pitch, volume, locale);

  // Somebody may have asked for this exact line while the browser was checking; send it there.
  if (url) {
    const cached = await fetch(publicUrl(url, key), { method: "HEAD" }).then((r) => r.ok).catch(() => false);
    if (cached) return Response.redirect(publicUrl(url, key), 302);
  }

  let audio;
  try {
    // Девять секунд из десяти, что даёт Netlify: остаток нужен на запись в хранилище и ответ.
    // Без бюджета две попытки складывались в 46 секунд, и платформа убивала функцию раньше,
    // чем та успевала сказать, что именно пошло не так.
    audio = await synthesise({ text, voice, locale, rate, pitch, volume, budgetMs: 9000 });
  } catch (e) {
    console.error("[tts]", e?.message || e);
    // The app falls back to the browser's own voice on any failure here, so this must be quick
    // and honest rather than retried until the function times out.
    return json({ error: "Голос сейчас недоступен." }, 503);
  }

  // Store it and move on — Emil should not wait for the upload to finish to hear the line.
  if (url && serviceKey) {
    putClip(url, serviceKey, key, audio).catch((e) => console.error("[tts] store", e?.message || e));
  }

  return new Response(audio, {
    headers: {
      "content-type": "audio/mpeg",
      "cache-control": "public, max-age=31536000, immutable",
      "x-tts-key": key,
    },
  });
};

export const config = { path: "/api/tts" };
